1.	Write a Python Program to Add Two Matrices?

In [5]:
import numpy as np
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
def add(x1,x2):
    return np.add(x1, x2)
add(x1,x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

2.	Write a Python Program to Multiply Two Matrices?

In [6]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
def multiply(x1,x2):
    return np.matmul(a, b)
multiply(a,b)

array([[4, 1],
       [2, 2]])

3.	Write a Python Program to Transpose a Matrix?

In [9]:
x = np.arange(4).reshape((2,2))
def transpose(x):
    return np.transpose(x)
transpose(x)

array([[0, 2],
       [1, 3]])

4.	Write a Python Program to Sort Words in Alphabetic Order?

In [12]:
def sort_words(str):
    str = input("Enter a string: ")  
    words = str.split() 
    words.sort()  
    for element in words:
        print(element) 

In [13]:
sort_words(str)

Enter a string: I am a student of FSDS batch
FSDS
I
a
am
batch
of
student


5.	Write a Python Program to Remove Punctuation From a String?

In [23]:
def remove_punc(str):
    punc='!"#$%&\'()*+,-./:;<=>?@[\]^_`{|}~'
    a=len(str)
    while a>0:
        for element in str:
            if element in punc:
                str=str.replace(element,'')
            a=a-1
            continue
        return str

In [26]:
remove_punc('I !am a /student of =FSDS ''Batch')

'I am a student of FSDS Batch'